databases:
  - name: kylibyakadb
    plan: free
    databaseName: kylibyaka
    user: kylibyaka

services:
  - type: web
    plan: free
    name: kylibyaka
    runtime: python
    buildCommand: 'cd kylibyaka && ./render_build.sh'
    startCommand: 'cd kylibyaka && ./render_start.sh'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kylibyakadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4